function [ID,static,loitering,move_forward,move_cw,move_ccw,waggle] = importfile6D(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [ID,STATIC,LOITERING,MOVE_FORWARD,MOVE_CW,MOVE_CCW,WAGGLE] =
%   IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [ID,STATIC,LOITERING,MOVE_FORWARD,MOVE_CW,MOVE_CCW,WAGGLE] =
%   IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [ID,static,loitering,move_forward,move_cw,move_ccw,waggle] = importfile1('individual_info.csv',1, 142);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/05/18 12:30:45

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ID = dataArray{:, 1};
static = dataArray{:, 2};
loitering = dataArray{:, 3};
move_forward = dataArray{:, 4};
move_cw = dataArray{:, 5};
move_ccw = dataArray{:, 6};
waggle = dataArray{:, 7};


